name: Testing and Linting

on:
  push:
    branches:
      - main
      - develop
      - hotfix/*
      - release/*
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: JimmyTournemaine/ha-core
        path: ${{ github.workspace }}/ha-core
    - uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/ha-knocki
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Run HA setup script
      run: |
        script/setup
        source venv/bin/activate
        pip3 install -r requirements_test_all.txt
      working-directory: ${{ github.workspace }}/ha-core
    - name: Merge ha-knocki in core
      run: |
        ln -s "${{ github.workspace }}/ha-knocki/knocki" "${{ github.workspace }}/ha-core/homeassistant/components/knocki"
        ln -s "${{ github.workspace }}/ha-knocki/tests" "${{ github.workspace }}/ha-core/tests/components/knocki"
      # ln -s "${{ github.workspace }}/ha-knocki/blueprints/automation" "${{ github.workspace }}/ha-core/config/blueprints/automation/knocki"
    - name: Test with pytest
      run: |
        source venv/bin/activate
        pytest tests/components/knocki --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      working-directory: ${{ github.workspace }}/ha-core
    - name: Lint with Ruff
      run: |
        source venv/bin/activate
        ruff --output-format=github ./homeassistant/components/knocki ./tests/components/knocki
      working-directory: ${{ github.workspace }}/ha-core
      continue-on-error: true
