# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: JimmyTournemaine/ha-core
        path: ${{ github.workspace }}/ha-core
    - uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/ha-knocki
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Run HA setup script
      run: script/setup
      working-directory: ./ha-core
    - name: Merge ha-knocki in core
      run: |
        ln -s "${{ github.workspace }}/ha-knocki/knocki" "${{ github.workspace }}/ha-core/homeassistant/components/knocki"
        ln -s "${{ github.workspace }}/ha-knocki/tests" "${{ github.workspace }}/ha-core/tests/components/knocki"
      # ln -s "${{ github.workspace }}/ha-knocki/blueprints/automation" "${{ github.workspace }}/ha-core/config/blueprints/automation/knocki"
    
